### ISSUE TITLE
Flashcards removed during drag-n-drop

### ISSUE THREAD

**Issue by CodeMagic** [subnotes/gemini#17]
I was playing around with the notebook explorer.  I had three flashcards in a subnote (Star Wars).  I created a child subnote (Wands) and sibling subnote (Harry Potter), then moved the child to the sibling (Wands from Star Wars to Harry Potter) and created a new flashcard in the child (Wands).  But I noticed afterward that the flashcards in the original subnote (Star Wars) were gone.  Not sure where along the process it happened, need to do more testing.

**Comment by chris-brackett** [comment]
Fixed. Flashcards were not properly updating to the notebook, causing them to be displayed only until the tree re-rendered and then they were lost. Flashcards now properly update the notebook directly and this bug no longer occurs.
